### ISSUE TITLE
Feature request: Add sha256 hash to verify installer is whats expected

### ISSUE THREAD

**Issue by vincecima** [lvillani/just-install#106]

**Comment by lvillani** [comment]
Every supported installer package already ships with internal consistency checks (e.g.: zip files have CRC32 checksums which are weak but passable).

Adding another checksum would only ensure that what we are getting is really "installer for application X", which is burdensome to maintain in case we have to update a lot of entries in the registry. I recognize that this improves security since we won't blindingly download and run a random executable from the Internet.

I could add a command to automatically (and blindingly) fetch and update the checksum in the registry but that would defeat the purpose of the checksum, so any update would have to be done manually by downloading the installer locally and ensuring it is what we expect it to be.

So, on one side I'm :+1: about this but I'm not going to be working on this personally for the time being because I fear that it would increase the load required to maintain the registry. I might implement this in the future. Meanwhile, if you want to submit a PR to implement this feature I'll be happy to review it.

**Comment by lvillani** [comment]
I'm closing it for now, since I don't really have the time to work on this. Will re-open in the future.
