### ISSUE TITLE
Feature Request: Add ability to see package version from the command line

### ISSUE THREAD

**Issue by guiweber** [lvillani/just-install#149]
It would be nice to be able to do something like:
`just-install -v vlc`

which would output something like:
`vlc version 2.2.2`

**Comment by lvillani** [comment]
I'll include the output in `just-install list`

**Comment by guiweber** [comment]
Sounds good. Could you make it so that if a package (or a list of packages) is present after the list command, only those packages are listed then? That way we don't have to scroll through the list to find it.

**Comment by lvillani** [comment]
If you are using PowerShell you can then e.g. `just-install list | select-string vlc` to filter out results

**Comment by guiweber** [comment]
Unfortunately I am not. But if outputting a single package is not an option, having the version number in the list will be better than nothing.

**Comment by lvillani** [comment]
`cmd.exe` has `findstr`, so something like `just-install list | findstr vlc` should also work. I come from the UNIX school where filtering is done by a dedicated utility 😄

**Comment by guiweber** [comment]
Thanks for the tip!

**Comment by lvillani** [comment]
By the way, this should be in the latest beta that you can install by running `msiexec /i http://beta.just-install.it`

**Comment by davidpaige** [comment]
I can't figure out how to prevent the command window from closing when I run a just-install list.

Also, it might be nice to have an optional switch (maybe /passive) that shows the standard msi passive window, so you can see that just-install is working.

**Comment by guiweber** [comment]
I'm not seeing this issue. Are you running the command from a batch file or a shortcut?

**Comment by lvillani** [comment]
@davidpaige just-install runs as a privileged application, so if you run it from a non-administrative command prompt, it will open an administrative one first (by going through UAC) and closing it when just-install exits. This is standard Windows behavior. It's something that I could change but I don't because I don't have time to spend on this particular issue.

The work-around is simple: open an administrative command prompt first (right click cmd.exe and click on "Run as Administrator") and invoke just-install from there.
