### ISSUE TITLE
Offline support?

### ISSUE THREAD

**Issue by MSumulong** [lvillani/just-install#85]
Is there currently support to have an installer .exe file to be located locally on a machine? I'd like to use just-install on machines that aren't regularly connected to the internet.

**Comment by lvillani** [comment]
Yes and no, as of now, just-install downloads installers to `%Temp%`. If you look there you will find some executables with eight-letters hexadecimal names, these are the CRC-32 of the download URL for each installer.

Since this is a useful feature request I will push a new version that saves both the .json file and all installers under `%Temp%\just-install`, that should make it easier to sync the directory between machines.

**Comment by lvillani** [comment]
I'll also add a `--download-only` switch so that you can download all installers on one machine, then zip up `%Temp%\just-install%` and copy on another machine.

**Comment by MSumulong** [comment]
Awesome! That would help tremendously. I'll close this out after this is implemented.

**Comment by lvillani** [comment]
I'll try to carve out some time this weekend.

**Comment by lvillani** [comment]
Can you try to install the latest beta by running `msiexec.exe /i http://beta.just-install.it`?

**Comment by MSumulong** [comment]
Works as expected, thanks!
