### ISSUE TITLE
[question] Using insite repository

### ISSUE THREAD

**Issue by Pafzedog** [lvillani/just-install#95]
Hello,
Is there a way to work with a custom repository like a network share or webserver on my corporate LAN.

first I will be able to make some custom installers and in a second time it will save some bandwidth in case of massive deployment .

thanks

**Comment by Pafzedog** [comment]
ok, sorry for that dumb question :/ 
I just have to modify justinstall.json ...

**Comment by lvillani** [comment]
Well.. just-install fetches installation packages directly from upstream servers, it has no notion of a repository. If you have a large network I guess you could add a transparent HTTP proxy in front of your LAN's gateway so that installers are automatically cached without having to change just-install or just-install.json.

Setting up e.g.: Squid for interception caching should be relatively easy. You may have to do a little more work for installers served over HTTPS though.

**Comment by Pafzedog** [comment]
really a good idea, thanks !
I will have a look at this and try it
I'll make a report here.
